### ISSUE TITLE
MMR attribute fixes

### ISSUE THREAD

**Issue by inodb** [clinical-data-mining/msk_cdm#29]
- [ ] “MMR (NLP)” and value “deficient/proficient” - MMR deficient  and then Yes/No values is harder to understand imo
- [ ] Use same in timeline:
    <img width="322" alt="image" src="https://github.com/clinical-data-mining/msk_cdm/assets/1334004/96f2c8de-cf98-4e13-ace4-73b121d50806">
- [ ] On timeline change Source attribute from “CDM” to “Pathology Report (CDM)”. Same as it is for e.g. Tumor Sites

**Comment by fongcj** [comment]
Changes made but won't see results on portal until Airflow DAGs are back online.
